spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/retowebflux
    username: root
    password: 123456789
  main:
    allow-bean-definition-overriding: true

server:
  port: 8082

appDescription: "Bootcamp System"
appVersion: "1.0"
client:
  capability: "http://localhost:8081/capability"